//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÁN VÉ.
        /// </summary>
        public static string BanVe {
            get {
                return ResourceManager.GetString("BanVe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÀI ĐẶT.
        /// </summary>
        public static string CAIDAT {
            get {
                return ResourceManager.GetString("CAIDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt hệ thống.
        /// </summary>
        public static string CaiDatHeThong {
            get {
                return ResourceManager.GetString("CaiDatHeThong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÁ NHÂN.
        /// </summary>
        public static string CANHAN {
            get {
                return ResourceManager.GetString("CANHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn màu.
        /// </summary>
        public static string ChonMau {
            get {
                return ResourceManager.GetString("ChonMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string DangXuat {
            get {
                return ResourceManager.GetString("DangXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string DiaChi {
            get {
                return ResourceManager.GetString("DiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string HoVaTen {
            get {
                return ResourceManager.GetString("HoVaTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu chữ.
        /// </summary>
        public static string KieuChu {
            get {
                return ResourceManager.GetString("KieuChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương giờ.
        /// </summary>
        public static string LuongGio {
            get {
                return ResourceManager.GetString("LuongGio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thay đổi.
        /// </summary>
        public static string LuuThayDoi {
            get {
                return ResourceManager.GetString("LuuThayDoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu sắc.
        /// </summary>
        public static string MauSac {
            get {
                return ResourceManager.GetString("MauSac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string NgaySinh {
            get {
                return ResourceManager.GetString("NgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string NgonNgu {
            get {
                return ResourceManager.GetString("NgonNgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHÂN SỰ.
        /// </summary>
        public static string NHANSU {
            get {
                return ResourceManager.GetString("NHANSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHIM.
        /// </summary>
        public static string PHIM {
            get {
                return ResourceManager.GetString("PHIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHÒNG CHIẾU.
        /// </summary>
        public static string PHONGCHIEU {
            get {
                return ResourceManager.GetString("PHONGCHIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SẢN PHẨM.
        /// </summary>
        public static string SANPHAM {
            get {
                return ResourceManager.GetString("SANPHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string SoDienThoai {
            get {
                return ResourceManager.GetString("SoDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUẤT CHIẾU.
        /// </summary>
        public static string SUATCHIEU {
            get {
                return ResourceManager.GetString("SUATCHIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string TenDangNhap {
            get {
                return ResourceManager.GetString("TenDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÊM NHÂN SỰ.
        /// </summary>
        public static string ThemNhanSu {
            get {
                return ResourceManager.GetString("ThemNhanSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên.
        /// </summary>
        public static string ThemNhanVien {
            get {
                return ResourceManager.GetString("ThemNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cá nhân.
        /// </summary>
        public static string ThongTinCaNhan {
            get {
                return ResourceManager.GetString("ThongTinCaNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANG CHỦ.
        /// </summary>
        public static string TRANGCHU {
            get {
                return ResourceManager.GetString("TRANGCHU", resourceCulture);
            }
        }
    }
}
