//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÀI ĐẶT.
        /// </summary>
        public static string CAIDAT {
            get {
                return ResourceManager.GetString("CAIDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÁ NHÂN.
        /// </summary>
        public static string CANHAN {
            get {
                return ResourceManager.GetString("CANHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHÂN SỰ.
        /// </summary>
        public static string NHANSU {
            get {
                return ResourceManager.GetString("NHANSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHIM.
        /// </summary>
        public static string PHIM {
            get {
                return ResourceManager.GetString("PHIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHÒNG CHIẾU.
        /// </summary>
        public static string PHONGCHIEU {
            get {
                return ResourceManager.GetString("PHONGCHIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUẤT CHIẾU.
        /// </summary>
        public static string SUATCHIEU {
            get {
                return ResourceManager.GetString("SUATCHIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANG CHỦ.
        /// </summary>
        public static string TRANGCHU {
            get {
                return ResourceManager.GetString("TRANGCHU", resourceCulture);
            }
        }
    }
}
